name: Build and Push to Harbor

on:
  push:
    branches:
      - mattermost-taruvi
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fetch secrets from Infisical
      - name: Get environment variables from Infisical
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env-slug: taruvi-test
          project-slug: ${{ vars.TARUVI_PROJECT_SLUG }}
          secret-path: /Mattermost
          domain: "https://environment.eoxvantage.com"

      - name: Create .env file for Docker build
        run: |
          printenv | grep -E '^(MM_|AWS_|ALLOW|API_)' > .env
          cat .env

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: repo.eoxvantage.com
          username: ${{ env.HARBOR_USERNAME }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=registry,ref=repo.eoxvantage.com/taruvi/mattermost:buildcache
          cache-to: type=registry,ref=repo.eoxvantage.com/taruvi/mattermost:buildcache,mode=max
          tags: |
            repo.eoxvantage.com/taruvi/mattermost:latest
            repo.eoxvantage.com/taruvi/mattermost:${{ github.sha }}
