name: Build and Push to Harbor

on:
  push:
    branches:
      - mattermost-taruvi
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          MM_SQLSETTINGS_DATASOURCE=${{ secrets.MM_SQLSETTINGS_DATASOURCE }}
          EOF

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: repo.eoxvantage.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push
        run: |
          cd server/build
          docker build -t repo.eoxvantage.com/taruvi/mattermost:latest -t repo.eoxvantage.com/taruvi/mattermost:${{ github.sha }} .
          docker push repo.eoxvantage.com/taruvi/mattermost:latest
          docker push repo.eoxvantage.com/taruvi/mattermost:${{ github.sha }}
