name: Build and Push to Harbor Taruvi

on:
  push:
    branches:
      - mattermost-taruvi
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fetch secrets from Infisical
      - name: Get environment variables from Infisical
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env-slug: taruvi-test
          project-slug: ${{ vars.TARUVI_PROJECT_SLUG }}
          secret-path: /Mattermost
          domain: "https://environment.eoxvantage.com"

      - name: Create .env file
        run: |
          printenv | grep -E '^(MM_|AWS_|ALLOW|API_)' > .env
          cat .env

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: repo.eoxvantage.com
          username: ${{ env.HARBOR_USERNAME }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          secret-files: |
            "envfile=.env"
          tags: |
            repo.eoxvantage.com/taruvi/mattermost:latest
            repo.eoxvantage.com/taruvi/mattermost:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

        
      - name: Restart Mattermost deployment
        run: |
          kubectl rollout restart mattermost mattermost-staging -n mattermost
          kubectl rollout status mattermost mattermost-staging --timeout=600s -n mattermost
