name: Server CI Artifacts

on:
  workflow_run:
    workflows:
      - "Server CI"
    types:
      - completed

jobs:
  build-docker:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: cd/docker-login
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: repo.eoxvantage.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: cd/download-artifacts-from-PR-workflow
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: server-build-artifact
          path: server/build/

      - name: cd/setup-docker-buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: cd/set-docker-tag
        id: set_tag
        run: |
          echo "TAG=$(echo '${{ github.event.workflow_run.head_sha }}' | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: cd/docker-build-and-push
        env:
          TAG: ${{ steps.set_tag.outputs.TAG }}
        run: |
          cd server/build
          docker buildx build --no-cache --platform linux/amd64 --push -t repo.eoxvantage.com/mattermost/mattermost:${TAG} -t repo.eoxvantage.com/mattermost/mattermost:latest .

      - name: cd/generate-summary
        env:
          TAG: ${{ steps.set_tag.outputs.TAG }}
        run: |
          echo "### Docker Image Built" >> "${GITHUB_STEP_SUMMARY}"
          echo "Image: \`repo.eoxvantage.com/mattermost/mattermost:${TAG}\`" >> "${GITHUB_STEP_SUMMARY}"
          echo "Latest: \`repo.eoxvantage.com/mattermost/mattermost:latest\`" >> "${GITHUB_STEP_SUMMARY}"
